### ISSUE TITLE
docker-compose up docker 1.12.1

### ISSUE THREAD

**Issue by oceanshy** [beia/switch#2]
ERROR: Service 'web' failed to build: The command '/bin/sh -c true 	&& apt-key adv --keyserver hkp://pgp.mit.edu:80 --recv-keys 573BFD6B3D8FBC641079A6ABABF5BD827BD9BF62 	&& echo "deb http://nginx.org/packages/mainline/debian/ jessie nginx" >> /etc/apt/sources.list 	&& apt-get update 	&& apt-get install --no-install-recommends --no-install-suggests -y 		ca-certificates 		nginx=${NGINX_VERSION:-1.11.6-1~jessie} 		nginx-module-xslt 		nginx-module-geoip 		nginx-module-image-filter 		gettext-base 		php5-fpm php5-mysql 		supervisor 	&& mkdir -p /run/php 	&& rm -rf /var/lib/apt/lists/*' returned a non-zero code: 100

**Comment by vladwing** [comment]
It's fixed in recent versions.
